<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Example.FullFlow</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Capisoft.Lib.SharpCursorCli\Capisoft.Lib.SharpCursorCli.csproj" />
    <ProjectReference Include="..\..\src\Capisoft.Lib.SharpCursorCli.Storage\Capisoft.Lib.SharpCursorCli.Storage.csproj" />
  </ItemGroup>
</Project>
